### ISSUE TITLE
cblas.h ? 

### ISSUE THREAD

**Issue by kaneyxx** [ElofssonLab/pyGaussDCA#6]
I git clone the repo and use command python setup.py
and error occured, I'm using MacOS Catalina. Could you help me to solve this?

```
/var/folders/6f/0ftf_13s0452p6ns280cdv_h0000gn/T/tmp9cj_7gl9/source.c:1:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^~~~~~~~~
1 error generated.
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

**Comment by arneelof** [comment]
Try to use these versions
keras==2.2.4
2.0< tensorflow >=1.12.
pythran 0.9.5

Yours

Arne

-----------------------------------------
  Arne Elofsson                  Science for Life Laboratory
  Tel:+46-(0)70 695 1045   Stockholm University
  http://bioinfo.se/               Box 1031,
  Email: arne@bioinfo.se   17121 Solna, Sweden
  Twitter:   https://twitter.com/arneelof
  Scholar: http://scholar.google.se/citations?user=s3OCM3AAAAAJ
  ORCID: 0000-0002-7115-9751

**Comment by jwelliav** [comment]
Hi Arne,

     I am having the same issue and I have done as you suggested. On a virtual environment, I am using keras==2.2.4, pythran==0.9.5 and tensorflow 1.13.1 ( I also tried tensorflow 1.15). None of these worked. 
This is the error message I am getting. 


    ERROR: Command errored out with exit status 1:
     command: /Users/johnwelliaveetil/python-virtual-environments/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-install-3vkn7ve2/pygaussdca/setup.py'"'"'; __file__='"'"'/private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-install-3vkn7ve2/pygaussdca/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-6hz9fmt1
         cwd: /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-install-3vkn7ve2/pygaussdca/
    Complete output (80 lines):
    /var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/tmpdwihy5rb/source.c:1:10: fatal error: 'cblas.h' file not found
    #include <cblas.h>
             ^~~~~~~~~
    1 error generated.
    running egg_info
    creating /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-6hz9fmt1/pyGaussDCA.egg-info
    writing /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-6hz9fmt1/pyGaussDCA.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-6hz9fmt1/pyGaussDCA.egg-info/dependency_links.txt
    writing requirements to /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-6hz9fmt1/pyGaussDCA.egg-info/requires.txt
    writing top-level names to /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-6hz9fmt1/pyGaussDCA.egg-info/top_level.txt
    writing manifest file '/private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-6hz9fmt1/pyGaussDCA.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-install-3vkn7ve2/pygaussdca/setup.py", line 35, in <module>
        zip_safe=False)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/sdist.py", line 312, in _add_defaults_ext
        self.filelist.extend(build_ext.get_source_files())
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 426, in get_source_files
        filenames.extend(ext.sources)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/dist.py", line 154, in sources
        module_name, cpponly=True)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/toolchain.py", line 479, in compile_pythranfile
        **kwargs)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/toolchain.py", line 402, in compile_pythrancode
        module_dir)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/toolchain.py", line 153, in generate_cxx
        entry_points=entry_points)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/toolchain.py", line 116, in front_middle_end
        refine(pm, ir, optimizations)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/middlend.py", line 23, in refine
        pm.apply(NormalizeTuples, node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 235, in apply
        return a.apply(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 198, in apply
        new_node = self.run(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 186, in run
        n = super(Transformation, self).run(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 96, in run
        return self.visit(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
        return super(ContextManager, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 326, in generic_visit
        value = self.visit(value)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
        return super(ContextManager, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/transformations/normalize_tuples.py", line 196, in visit_FunctionDef
        return self.generic_visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 326, in generic_visit
        value = self.visit(value)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
        return super(ContextManager, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/transformations/normalize_tuples.py", line 154, in visit_Assign
        gload)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/transformations/normalize_tuples.py", line 151, in <lambda>
        ast.Index(ast.Constant(y, None)),
    AttributeError: module 'gast' has no attribute 'Index'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


Please let me know what you suggest. 

     Thanks in advance,

          John

**Comment by arneelof** [comment]
Try to use the implementation from PconsC4 - that one I know works.

Yours

Arne

-----------------------------------------
  Arne Elofsson                  Science for Life Laboratory
  Tel:+46-(0)70 695 1045   Stockholm University
  http://bioinfo.se/               Box 1031,
  Email: arne@bioinfo.se   17121 Solna, Sweden
  Twitter:   https://twitter.com/arneelof
  Scholar: http://scholar.google.se/citations?user=s3OCM3AAAAAJ
  ORCID: 0000-0002-7115-9751

**Comment by jwelliav** [comment]
Thanks Arne for the quick reply. I tried as you suggested - pip install pconsc4. But once again the installation failed when it tried to install pyGaussDCA. 

  ERROR: Command errored out with exit status 1:
     command: /Users/johnwelliaveetil/python-virtual-environments/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-install-b4ylu36_/pygaussdca/setup.py'"'"'; __file__='"'"'/private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-install-b4ylu36_/pygaussdca/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-fvv2agpk
         cwd: /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-install-b4ylu36_/pygaussdca/
    Complete output (112 lines):
    /var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/tmpobjrgpyv/source.c:1:10: fatal error: 'cblas.h' file not found
    #include <cblas.h>
             ^~~~~~~~~
    1 error generated.
    running egg_info
    creating /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-fvv2agpk/pyGaussDCA.egg-info
    writing /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-fvv2agpk/pyGaussDCA.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-fvv2agpk/pyGaussDCA.egg-info/dependency_links.txt
    writing requirements to /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-fvv2agpk/pyGaussDCA.egg-info/requires.txt
    writing top-level names to /private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-fvv2agpk/pyGaussDCA.egg-info/top_level.txt
    writing manifest file '/private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-pip-egg-info-fvv2agpk/pyGaussDCA.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/04/8kypjgdn3bv40c8xb0qsh3nc0000gn/T/pip-install-b4ylu36_/pygaussdca/setup.py", line 35, in <module>
        zip_safe=False)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 298, in run
        self.find_sources()
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 305, in find_sources
        mm.run()
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 536, in run
        self.add_defaults()
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/sdist.py", line 312, in _add_defaults_ext
        self.filelist.extend(build_ext.get_source_files())
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 426, in get_source_files
        filenames.extend(ext.sources)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/dist.py", line 154, in sources
        module_name, cpponly=True)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/toolchain.py", line 479, in compile_pythranfile
        **kwargs)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/toolchain.py", line 402, in compile_pythrancode
        module_dir)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/toolchain.py", line 153, in generate_cxx
        entry_points=entry_points)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/toolchain.py", line 116, in front_middle_end
        refine(pm, ir, optimizations)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/middlend.py", line 20, in refine
        pm.apply(RemoveDeadFunctions, node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 235, in apply
        return a.apply(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 198, in apply
        new_node = self.run(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 186, in run
        n = super(Transformation, self).run(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 95, in run
        self.prepare(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 90, in prepare
        result = d.run(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 143, in run
        return super(ModuleAnalysis, self).run(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 123, in run
        super(Analysis, self).run(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 96, in run
        return self.visit(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
        return super(ContextManager, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/analyses/use_def_chain.py", line 52, in visit_Module
        duc.visit(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/analyses/use_def_chain.py", line 23, in visit
        return super(ExtendedDefUseChains, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/beniget/beniget.py", line 358, in visit_Module
        visitor(fnode, step=DefinitionStep)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/beniget/beniget.py", line 424, in visit_FunctionDef
        self.process_body(node.body)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/beniget/beniget.py", line 292, in process_body
        self.visit(stmt)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/analyses/use_def_chain.py", line 23, in visit
        return super(ExtendedDefUseChains, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/beniget/beniget.py", line 465, in visit_Assign
        self.visit(node.value)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/analyses/use_def_chain.py", line 23, in visit
        return super(ExtendedDefUseChains, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/beniget/beniget.py", line 726, in visit_BinOp
        self.visit(node.right).add_user(dnode)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/analyses/use_def_chain.py", line 23, in visit
        return super(ExtendedDefUseChains, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/beniget/beniget.py", line 725, in visit_BinOp
        self.visit(node.left).add_user(dnode)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/analyses/use_def_chain.py", line 23, in visit
        return super(ExtendedDefUseChains, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/beniget/beniget.py", line 725, in visit_BinOp
        self.visit(node.left).add_user(dnode)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/pythran/analyses/use_def_chain.py", line 23, in visit
        return super(ExtendedDefUseChains, self).visit(node)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 271, in visit
        return visitor(node)
      File "/Users/johnwelliaveetil/python-virtual-environments/env/lib/python3.7/site-packages/beniget/beniget.py", line 847, in visit_Subscript
        self.visit(node.slice).add_user(dnode)
    AttributeError: 'NoneType' object has no attribute 'add_user'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by arneelof** [comment]
Not really sure, my guess is that it might be python3.7 I think we used 3.5
(or possible 3.6) it was developed some years ago and no one worked with it
lately

Yours

Arne

-----------------------------------------
  Arne Elofsson                  Science for Life Laboratory
  Tel:+46-(0)70 695 1045   Stockholm University
  http://bioinfo.se/               Box 1031,
  Email: arne@bioinfo.se   17121 Solna, Sweden
  Twitter:   https://twitter.com/arneelof
  Scholar: http://scholar.google.se/citations?user=s3OCM3AAAAAJ
  ORCID: 0000-0002-7115-9751

**Comment by jwelliav** [comment]
Thanks once again for the immediate response. I will try this and get back to you. 

Best wishes,

      John
